export interface IUser {
    ID?:number,
    DOM_ID_GENDER?:number|null,
    DOM_ID_USER_TYPE?:number|null,
    NAME?: string|null,
    FAMILY?: string|null,
    NATIONAL_CODE?: string|null,
    PHONE?: string|null,
    MOBILE?: string|null,
    IMAGE_USER?: string|null,
    USER_NAME?: string|null,
    PASSWORD?: string|null,
    EMAIL?: string|null,
    ADDRESS?: string|null,
    START_DATE_TIME?: number|null,
    END_DATE_TIME?: number|null,
    IS_ACTIVE?: boolean|null,
    DESCRIPTION?: string|null,
    USE_ID_CREATOR?: number|null,
    CREATE_DATE_TIME?: number|null,
    MODIFY_USE_ID?: number|null,
    MODIFY_DATE_TIME?: number|null,
    FULL_NAME?:string,
}
